#include <Arduino.h>

#define i2c_display_address 0x3C
#define i2c_INA_address 0x40

//##### INA226 THINGS ######
int input_voltage;
int output_voltage;
int input_amp;

void setup() {

}

void loop() {

}
